___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [447]:
import numpy as np

#### Create an array of 10 zeros 

In [448]:
arr = np.zeros(10)
print(arr)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


#### Create an array of 10 ones

In [449]:
arr_ones = np.ones(10)
print(arr_ones)

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


#### Create an array of 10 fives

In [450]:
arr_fives = np.arange(1,11)
arr_fives[:]=5
print(arr_fives)

[5 5 5 5 5 5 5 5 5 5]


#### Create an array of the integers from 10 to 50

In [451]:
arr_in = np.arange(10,50)
print(arr_in)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### Create an array of all the even integers from 10 to 50

In [452]:
arr_ine = np.arange(10,51,2)
print(arr_ine)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [453]:
arr = np.arange(0,9)
ashape = arr.reshape(3,3)
print(ashape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [454]:
i3 = np.eye(3)
print(i3)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


#### Use NumPy to generate a random number between 0 and 1

In [455]:
print(np.random.rand(1))

[ 0.83403094]


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [456]:
print(np.random.randn(25))

[-1.01690396 -1.86336503  1.89089727  0.26379135 -1.8659637  -0.24931037
  0.97929274  0.41381004  2.3068972  -1.15094975 -1.74976233 -0.12963111
 -0.67917175 -0.79622151 -0.20091334  0.73094236 -0.35805456 -0.87519079
 -0.19048032 -0.69368994  1.16476743 -0.06940518  1.60094257 -0.56935291
  0.97300982]


#### Create the following matrix:

#### Create an array of 20 linearly spaced points between 0 and 1:

In [457]:
print(np.linspace(0,1,20))

[ 0.          0.05263158  0.10526316  0.15789474  0.21052632  0.26315789
  0.31578947  0.36842105  0.42105263  0.47368421  0.52631579  0.57894737
  0.63157895  0.68421053  0.73684211  0.78947368  0.84210526  0.89473684
  0.94736842  1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [458]:
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [459]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [460]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [461]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [462]:
mat[3][4]

20

In [463]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [464]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [465]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [466]:
mat[4]

array([21, 22, 23, 24, 25])

In [467]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [468]:
mat[3:,0:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [469]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [470]:
mat.std()

7.2111025509279782

#### Get the sum of all the columns in mat

In [471]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

# Great Job!